kind: Namespace
apiVersion: v1
metadata:
  name: jhalo
  labels:
    name: jhalo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jhalo-deployment
  namespace: jhalo
  labels:
    app: jhalo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhalo
  template:
    metadata:
      labels:
        app: jhalo
    spec:
      nodeSelector:
        purpose: general
      containers:
        - name: jhalo
          image: agusba011/page:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: jhalo-service
  namespace: jhalo
spec:
  selector:
    app: jhalo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jhalo
  namespace: jhalo
spec:
  hosts:
    - '*'
  gateways:
    - istio-custom/devops-gateway
  http:
    - name: 'jhalo-routes'
      match:
        - uri:
            prefix: '/jhalo'
      route:
        - destination:
            host: jhalo-service.jhalo.svc.cluster.local